<a href="https://colab.research.google.com/github/ancestor9/Listeria/blob/main/Listeria_01_Extract_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
path ='/content/drive/MyDrive/MFDS/listeria_dataset.parquet'
df = pd.read_parquet(path)
df

,lims_data_key,hazard_label,judge_result,src_route,data_source,expr_iem_nm,result_value,result_value_num,judge_stdr,judge_stdr_num,...,train_prdlst_nm,prduct_nm,mnfctur_cmpny_nm,mnfctur_de,date_basis,addr,addr_source,legal_dong_code,lat,lon
0,O000001_160100193_1_2,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,"음성,음성,음성,음성,음성",NaN,<NA>,NaN,...,식육가공품 및 포장육,한우전통수제육포,윤솜씨,2016-02-11,제조일,"경기도 성남시 중원구 갈마치로 302, 우림라이온스밸리 5차 A동 1005호(상대원동)",제조사소재지,4113310500,37.433239,127.164383
1,O000001_160100103_5_4,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,0,0.0,<NA>,NaN,...,기타기준규격외,"화이트초콜릿 65℃, 30min",(주)쵸코하우스,2016-03-11,의뢰일,"경기도 성남시 중원구 둔촌대로 560(상대원동, 벽산테크노피아911,912,906,...",제조사소재지,4113310500,37.433239,127.164383
2,O000001_160100128_12_5,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,음성,NaN,<NA>,NaN,...,조미식품,미역국 농축 분말,(주)태진에프앤에스,2016-01-12,제조일,충청남도 천안시 서북구 입장면 위례성로 1929(기로리),제조사소재지,4413331000,36.912807,127.221169
3,O000001_160100300_4_4,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,음성,NaN,<NA>,NaN,...,기타기준규격외,열무(세척전),(주)해마루,2016-03-22,의뢰일,"경기도 평택시 안중읍 성해2길 63-66 (학현리, 1, 2층)",제조사소재지,4122025300,36.986122,126.931168
4,O000001_160100301_2_4,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,음성,NaN,<NA>,NaN,...,기타기준규격외,무(세척후),(주)해마루,2016-03-22,의뢰일,"경기도 평택시 안중읍 성해2길 63-66 (학현리, 1, 2층)",제조사소재지,4122025300,36.986122,126.931168
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676554,1471124_IFDC16100074_IFDC16100074_20161012_리스테...,리스테리아,불검출,overseas,식약처,리스테리아 모노사이토제네스,"음성,음성,음성,음성,음성",NaN,"n=5,c=0,m=0/25g",NaN,...,유가공품류,그릭요거트 10%,MEVGAL S.A.,2016-10-07,선적일,57100 KOUFALLA THESSALONIKI,해외제조업소,NaN,40.802879,22.616556
676555,O000079_IFDD19020098_IFDD19020098_20190212_리스테...,리스테리아,불검출,overseas,식약처,리스테리아 모노사이토제네스,"음성,음성,음성,음성,음성",NaN,"n=5, c=0, m=0/25g",NaN,...,유가공품류,데미날90,FRIESLANDCAMPINA DOMO,2018-12-17,선적일,BOTERDIEP WZ 45 9781 EL BEDUM,해외제조업소,NaN,53.309044,6.598637
676556,1471124_IFDH16030074_IFDH16030074_20160321_리스테...,리스테리아,불검출,overseas,식약처,리스테리아 모노사이토제네스,"음성,음성,음성,음성,음성",NaN,"n=5,c=0,m=0/25g",NaN,...,식육가공품 및 포장육,뉴올리언즈치킨봉,TYSON POULTRY (THAILAND) LIMITED,2016-03-07,선적일,42/6 M.4 Ongkarak Ongkarak Nakornnayok 26120,해외제조업소,NaN,14.078689,101.025925
676557,1471111_201600562279_201600562279_20160825_리스테...,리스테리아,불검출,overseas,식약처,리스테리아모노사이토제네스,음성,NaN,음성,NaN,...,수산물,"냉동다랑어(남방참다랑어,F,횟감)","YASHIMASHOJI CO.,LTD SHISHIHARA FACTORY",2016-08-23,선적일,"628-1 SHISHIHARA, SHIMIZU-KU, SHIZUOKA-CITY,SH...",해외제조업소,NaN,35.047607,138.512970
676558,1471124_IFD015120736_IFD015120736_20151230_리스테...,리스테리아,불검출,overseas,식약처,리스테리아 모노사이토제네스,"음성,음성,음성,음성,음성",NaN,"n=5,c=0,m=0/25g",NaN,...,유가공품,까멩베르 8포션,COMPAGNIE DES FROMAGES ET RICHESMONTS,2015-12-23,선적일,RTE D AUNAY 14500 VIRE,해외제조업소,NaN,48.931938,-0.582166

In [7]:
def summarize_df(df: pd.DataFrame) -> pd.DataFrame:
    # 데이터프레임의 각 컬럼별 데이터 타입, 결측치 수/비율, 대표값 5개를 요약한 DataFrame을 반환합니다.
    summary_data = []
    for col in df.columns:
        dtype = df[col].dtype
        n_unique = df[col].nunique()
        null_cnt = df[col].isnull().sum()
        null_ratio = round((null_cnt / len(df)) * 100, 2)
        unique_vals = df[col].dropna().unique()
        sample_vals = list(unique_vals[:7])

        summary_data.append({
            'Column': col,
            'N_Unique': n_unique,
            'Dtype': dtype,
            'Null_Count': null_cnt,
            'Null_Ratio(%)': null_ratio,
            'Sample_Values_5': sample_vals
        })

    return pd.DataFrame(summary_data)

In [8]:
summarize_df(df)

,Column,N_Unique,Dtype,Null_Count,Null_Ratio(%),Sample_Values_5
0,lims_data_key,676559,string[python],0,0.00,"[O000001_160100193_1_2, O000001_160100103_5_4,..."
1,hazard_label,1,category,0,0.00,[리스테리아]
2,judge_result,2,category,0,0.00,"[불검출, 검출]"
3,src_route,2,category,0,0.00,"[domestic, overseas]"
4,data_source,1,category,0,0.00,[식약처]
5,expr_iem_nm,4,category,0,0.00,"[리스테리아모노사이토제네스, 리스테리아 모노사이토제네스, 리스테리아 모노싸이토제네스..."
6,result_value,101,string[python],28,0.00,"[음성,음성,음성,음성,음성, 0, 음성, 음성(n=5), 불검출, 0, 0, 0,..."
7,result_value_num,4,float32,672778,99.44,"[0.0, 2.0, 10.0, 5.0]"
8,judge_stdr,17,string[python],669269,98.92,"[n=5,c=0,m=0/25g, n=5, c=0, m=0/25g, 음성 , n=..."
9,judge_stdr_num,6,float32,676489,99.99,"[100.0, 20.0, 0.5, 0.0, 25.0, 1000.0]"
10,inspct_instt_code,270,category,0,0.00,"[O000001, O000047, O000034, O000044, O000089, ..."
11,prdlst_code,1253,category,0,0.00,"[C0202040000000, Z3800100000000, C012107000000..."
12,train_prdlst_code,82,category,170,0.03,"[C0202000000000, Z3800000000000, C012100000000..."
13,train_prdlst_nm,74,category,0,0.00,"[식육가공품 및 포장육, 기타기준규격외, 조미식품, 기타식품류, 두부류또는묵류, 알..."
14,prduct_nm,279474,string[python],1,0.00,"[한우전통수제육포, 화이트초콜릿 65℃, 30min, 미역국 농축 분말, 열무(세척..."
15,mnfctur_cmpny_nm,19251,string[python],332397,49.13,"[윤솜씨, (주)쵸코하우스, (주)태진에프앤에스, (주)해마루, (주)씨즈닝테크, ..."
16,mnfctur_de,3909,datetime64[ms],0,0.00,"[2016-02-11 00:00:00, 2016-03-11 00:00:00, 201..."
17,date_basis,3,category,0,0.00,"[제조일, 의뢰일, 선적일]"
18,addr,41311,string[python],0,0.00,"[경기도 성남시 중원구 갈마치로 302, 우림라이온스밸리 5차 A동 1005호(상대..."
19,addr_source,4,category,0,0.00,"[제조사소재지, 인허가대장, 업소주소, 해외제조업소]"
20,legal_dong_code,3769,category,47659,7.04,"[4113310500, 4413331000, 4122025300, 361103800..."
21,lat,6655,float32,0,0.00,"[37.43324, 36.912807, 36.986122, 36.655933, 36..."
22,lon,6629,float32,0,0.00,"[127.16438, 127.22117, 126.93117, 127.264114, ..."

### 의문사항
- result_value의 "음성,음성,음성,음성,음성" 의미는?

In [12]:
df['judge_result'].value_counts(normalize=True)*100

judge_result
불검출    99.708525
검출      0.291475
Name: proportion, dtype: float64

In [39]:
# @title 식품종류별로 검사결과 검출이 된 품목과 검측률
df['judge_result_numeric'] = df['judge_result'].map({'검출': 1, '불검출': 0}).astype(int)
product_list_tm = df.groupby('train_prdlst_nm')['judge_result_numeric'].mean().sort_values(ascending=False)*100
product_list_tm = product_list_tm[product_list_tm != 0]
product_list_tm

/tmp/ipykernel_1445/1969266631.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  product_list_tm = df.groupby('train_prdlst_nm')['judge_result_numeric'].mean().sort_values(ascending=False)*100

train_prdlst_nm
버섯류            13.043478
기타식물류           4.651163
건포류             3.225806
정액,수정란,종란       2.233779
축산물             1.617562
수산가공식품류         0.620985
수산물             0.542773
규격외일반가공식품       0.436205
빵또는떡류           0.371747
견과 종실류          0.342466
식육가공품 및 포장육     0.319701
기타기준규격외         0.271063
즉석식품류           0.127385
기타식품류           0.077316
유가공품            0.068050
알가공품            0.038760
유가공품류           0.031320
음료류             0.016160
빙과류             0.009007
Name: judge_result_numeric, dtype: float64

In [23]:
print(f'검출율이 "0"이 아닌 식품종류 개수는 {len(product_list_tm)} 종류')

검출율이 "0"이 아닌 식품종류 개수는 19 종류

In [50]:
# @리스테리아가 검출된 식품종류만 선택하여 데이터 구성
product_list_non_tm = product_list_tm[product_list_tm == 0]
print(product_list_non_tm.index)
tf = df[df['train_prdlst_nm'].isin(product_list_tm.index)]
print("tf['train_prdlst_nm'] 열(Column)에 들어있는 상품명 중 product_list_non_tm.index에 존재하는 상품명이 단 하나라도 있는가?")
tf['train_prdlst_nm'].isin(product_list_non_tm.index).any()

CategoricalIndex([], categories=['가공식품(전부개정)', '개별인정원료', '건포류', '견과 종실류', ..., '특수의료용도식품', '혼합제제류', '환경검체', '환경오염도조사용'], ordered=False, dtype='category', name='train_prdlst_nm')
tf['train_prdlst_nm'] 열(Column)에 들어있는 상품명 중 product_list_non_tm.index에 존재하는 상품명이 단 하나라도 있는가?

np.False_

In [48]:
summarize_df(tf)

,Column,N_Unique,Dtype,Null_Count,Null_Ratio(%),Sample_Values_5
0,lims_data_key,617817,string[python],0,0.00,"[O000001_160100193_1_2, O000001_160100103_5_4,..."
1,hazard_label,1,category,0,0.00,[리스테리아]
2,judge_result,2,category,0,0.00,"[불검출, 검출]"
3,src_route,2,category,0,0.00,"[domestic, overseas]"
4,data_source,1,category,0,0.00,[식약처]
5,expr_iem_nm,4,category,0,0.00,"[리스테리아모노사이토제네스, 리스테리아 모노사이토제네스, 리스테리아 모노싸이토제네스..."
6,result_value,98,string[python],25,0.00,"[음성,음성,음성,음성,음성, 0, 음성, 음성(n=5), 불검출, 0, 0, 0,..."
7,result_value_num,4,float32,614110,99.40,"[0.0, 2.0, 10.0, 5.0]"
8,judge_stdr,16,string[python],610776,98.86,"[n=5,c=0,m=0/25g, n=5, c=0, m=0/25g, 음성 , n=..."
9,judge_stdr_num,6,float32,617747,99.99,"[100.0, 20.0, 0.5, 0.0, 25.0, 1000.0]"
10,inspct_instt_code,258,category,0,0.00,"[O000001, O000047, O000034, O000044, O000089, ..."
11,prdlst_code,803,category,0,0.00,"[C0202040000000, Z3800100000000, C012904000000..."
12,train_prdlst_code,22,category,0,0.00,"[C0202000000000, Z3800000000000, C012900000000..."
13,train_prdlst_nm,19,category,0,0.00,"[식육가공품 및 포장육, 기타기준규격외, 기타식품류, 알가공품, 유가공품, 규격외일..."
14,prduct_nm,260250,string[python],1,0.00,"[한우전통수제육포, 화이트초콜릿 65℃, 30min, 열무(세척전), 무(세척후),..."
15,mnfctur_cmpny_nm,15125,string[python],315661,51.09,"[윤솜씨, (주)쵸코하우스, (주)해마루, (주)씨즈닝테크, (주)클릭, 금난, (..."
16,mnfctur_de,3909,datetime64[ms],0,0.00,"[2016-02-11 00:00:00, 2016-03-11 00:00:00, 201..."
17,date_basis,3,category,0,0.00,"[제조일, 의뢰일, 선적일]"
18,addr,37155,string[python],0,0.00,"[경기도 성남시 중원구 갈마치로 302, 우림라이온스밸리 5차 A동 1005호(상대..."
19,addr_source,4,category,0,0.00,"[제조사소재지, 인허가대장, 업소주소, 해외제조업소]"
20,legal_dong_code,3627,category,46337,7.50,"[4113310500, 4122025300, 3611038000, 437703400..."
21,lat,6459,float32,0,0.00,"[37.43324, 36.986122, 36.655933, 36.97194, 36...."
22,lon,6434,float32,0,0.00,"[127.16438, 126.93117, 127.264114, 127.4833, 1..."
23,judge_result_numeric,2,int64,0,0.00,"[0, 1]"

In [52]:
# tf.groupby('train_prdlst_nm')['judge_result_numeric'].mean().sort_values(ascending=False)*100
tf.groupby('train_prdlst_nm', observed=True)['judge_result_numeric'].mean().sort_values(ascending=False) * 100

train_prdlst_nm
버섯류            13.043478
기타식물류           4.651163
건포류             3.225806
정액,수정란,종란       2.233779
축산물             1.617562
수산가공식품류         0.620985
수산물             0.542773
규격외일반가공식품       0.436205
빵또는떡류           0.371747
견과 종실류          0.342466
식육가공품 및 포장육     0.319701
기타기준규격외         0.271063
즉석식품류           0.127385
기타식품류           0.077316
유가공품            0.068050
알가공품            0.038760
유가공품류           0.031320
음료류             0.016160
빙과류             0.009007
Name: judge_result_numeric, dtype: float64

In [59]:
# @title 식품종류별로 수입 및 국내를 구분하여 검출룰을 판단
detection_rate_by_product_route = (
    tf.groupby(['train_prdlst_nm', 'src_route'], observed=True)['judge_result_numeric']
    .mean()
    .unstack('src_route')
    .fillna(0) * 100
)

# domestic(국내) 수치 기준으로 내림차순 정렬하여 출력
detection_rate_by_product_route.sort_values(by='domestic', ascending=False)

src_route         domestic  overseas
train_prdlst_nm
버섯류              13.043478  0.000000
기타식물류             4.651163  0.000000
건포류               3.225806  0.000000
정액,수정란,종란         2.233779  0.000000
축산물               0.931677  2.483660
수산가공식품류           0.660442  0.000000
수산물               0.639659  0.537097
규격외일반가공식품         0.436205  0.000000
빵또는떡류             0.373134  0.000000
견과 종실류            0.342466  0.000000
식육가공품 및 포장육       0.308817  0.497427
기타기준규격외           0.271076  0.000000
즉석식품류             0.127385  0.000000
기타식품류             0.077351  0.000000
알가공품              0.042283  0.000000
음료류               0.016407  0.000000
빙과류               0.010093  0.000000
유가공품류             0.008973  0.097639
유가공품              0.000000  0.193268

In [60]:
# @title 검출률 평균이 0보다 큰(양수인) 조합의 데이터만 tf에서 추출하여 tf_filtered
# 1. 식품종류 및 경로(domestic/overseas)별 평균(검출률) 계산
rates = tf.groupby(['train_prdlst_nm', 'src_route'], observed=True)['judge_result_numeric'].transform('mean')

# 2. 검출률 평균이 0보다 큰(0이 아닌) 행들만 필터링하여 tf_filtered 생성
tf_filtered = tf[rates > 0].copy()

# 결과 확인
print(f"기존 tf 행 수: {len(tf)}")
print(f"필터링 후 tf 행 수: {len(tf_filtered)}")

기존 tf 행 수: 617817
필터링 후 tf 행 수: 603397