<a href="https://colab.research.google.com/github/ancestor9/Listeria/blob/main/Listeria_01_Extract_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
path ='/content/drive/MyDrive/MFDS/listeria_dataset.parquet'
df = pd.read_parquet(path)
df

,lims_data_key,hazard_label,judge_result,src_route,data_source,expr_iem_nm,result_value,result_value_num,judge_stdr,judge_stdr_num,...,train_prdlst_nm_2,prduct_nm,mnfctur_cmpny_nm,mnfctur_de,date_basis,addr,addr_source,legal_dong_code,lat,lon
0,O002012_250100044_1_5,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,"음성,음성,음성,음성,음성",NaN,<NA>,NaN,...,즉석섭취.편의식품류,렌위치 NY 샌드위치,존쿡 쉐프의 키친(Johncook chef's kitchen),2025-10-11,제조일,경기도 안성시 미양면 제2공단2길 25,제조사소재지,4155034000,36.975372,127.215195
1,O000728_250103704_4_3,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,음성,NaN,<NA>,NaN,...,기타기준규격외,"삼치(국내산_해동,전처리,세척전)",영어조합법인 서풍,2025-04-28,의뢰일,전라남도 여수시 화양면 석교로 121,제조사소재지,4613033000,34.708126,127.613495
2,O000130_250700450_1_5,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,"음성,음성,음성,음성,음성",NaN,<NA>,NaN,...,산양유,숲속산양목장 산양유,임실 산양유,2025-06-09,의뢰일,전북특별자치도 임실군 신덕면 수지로 73-8,제조사소재지,5275036000,35.683971,127.178284
3,1471124_250703286_1_1,리스테리아,불검출,overseas,식약처,리스테리아모노사이토제네스,"음성,음성,음성,음성,음성",NaN,<NA>,NaN,...,치즈류,무게또 고르곤졸라 & 마스카포네,<NA>,2025-07-25,선적일,"VIA V.EMANUELE 62, 23815 INTROBIO (LECCO)",해외제조업소,NaN,45.977798,9.449053
4,O000168_250702030_2_1,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,"음성,음성,음성,음성,음성",NaN,<NA>,NaN,...,아이스크림류,뉴 쿠즈코초콜릿,(주)테이트,2025-08-11,제조일,경기도 광주시 오포읍 봉골길33번길 23,제조사소재지,4161025000,37.362312,127.213516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676526,O000858_250108768_4_6,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,음성,NaN,<NA>,NaN,...,기타기준규격외,별별생선까스 동결 후,(주)다미푸드,2025-05-19,의뢰일,경기도 광주시 초월읍 숯골길 17-42(1층),제조사소재지,4161025300,37.385250,127.287964
676527,O000858_250703099_3_4,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,"음성,음성,음성,음성,음성",NaN,<NA>,NaN,...,알가공품,에코팜 금 계란말이,영농조합법인 김포축산,2025-06-25,제조일,경기도 김포시 대곶면 대곶로 429-19,제조사소재지,4157034000,37.649372,126.582138
676528,O000169_250701159_29_1,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,음성,NaN,<NA>,NaN,...,기타기준규격외,편육 냉각,<NA>,2025-06-16,의뢰일,경기도 파주시 조리읍 등원로330번길 110,업소주소,4148026200,37.744717,126.805168
676529,O000728_250106788_12_3,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,음성,NaN,<NA>,NaN,...,기타기준규격외,유기농레몬즙100%(87℃/55분살균후),대동고려삼(주),2025-07-17,제조일,충청남도 금산군 군북면 군북로 586,제조사소재지,4471034000,36.168907,127.527725
676530,O000696_250700501_1_4,리스테리아,불검출,domestic,식약처,리스테리아모노사이토제네스,"음성,음성,음성,음성,음성",NaN,<NA>,NaN,...,알가공품,알찬 구운 유정란,<NA>,2025-08-05,제조일,경기도 용인시 처인구 원삼면 맹리로127번길 21,인허가대장,4146134000,37.166607,127.313202

In [3]:
def summarize_df(df: pd.DataFrame) -> pd.DataFrame:
    # 데이터프레임의 각 컬럼별 데이터 타입, 결측치 수/비율, 대표값 5개를 요약한 DataFrame을 반환합니다.
    summary_data = []
    for col in df.columns:
        dtype = df[col].dtype
        n_unique = df[col].nunique()
        null_cnt = df[col].isnull().sum()
        null_ratio = round((null_cnt / len(df)) * 100, 2)
        unique_vals = df[col].dropna().unique()
        sample_vals = list(unique_vals[:7])

        summary_data.append({
            'Column': col,
            'N_Unique': n_unique,
            'Dtype': dtype,
            'Null_Count': null_cnt,
            'Null_Ratio(%)': null_ratio,
            'Sample_Values_5': sample_vals
        })

    return pd.DataFrame(summary_data)

In [4]:
summarize_df(df)

,Column,N_Unique,Dtype,Null_Count,Null_Ratio(%),Sample_Values_5
0,lims_data_key,676531,string[python],0,0.00,"[O002012_250100044_1_5, O000728_250103704_4_3,..."
1,hazard_label,1,category,0,0.00,[리스테리아]
2,judge_result,2,category,0,0.00,"[불검출, 검출]"
3,src_route,2,category,0,0.00,"[domestic, overseas]"
4,data_source,1,category,0,0.00,[식약처]
5,expr_iem_nm,4,category,0,0.00,"[리스테리아모노사이토제네스, 리스테리아 모노사이토제네스, 리스테리아 모노싸이토제네스..."
6,result_value,100,string[python],0,0.00,"[음성,음성,음성,음성,음성, 음성, 불검출, 음성, 음성, 음성, 음성, 음성, ..."
7,result_value_num,2,float32,672754,99.44,"[0.0, 2.0]"
8,judge_stdr,17,string[python],669258,98.92,"[n=5,c=0,m=0/25g, n=5, c=0, m=0/25g, 음성 , 10..."
9,judge_stdr_num,5,float32,676463,99.99,"[100.0, 20.0, 25.0, 1000.0, 0.5]"
10,inspct_instt_code,270,category,0,0.00,"[O002012, O000728, O000130, 1471124, O000168, ..."
11,prdlst_code,1251,category,0,0.00,"[C0322020100000, Z3800100000000, C031803000000..."
12,train_prdlst_code,52,category,135,0.02,"[C0322000000000, Z3800000000000, C031800000000..."
13,train_prdlst_nm,53,category,0,0.00,"[즉석식품류, 기타기준규격외, 유가공품류, 빙과류, 조리식품 등, 농산가공식품류, ..."
14,train_prdlst_code_2,226,category,135,0.02,"[C0322020000000, Z3800100000000, C031803000000..."
15,train_prdlst_nm_2,226,category,0,0.00,"[즉석섭취.편의식품류, 기타기준규격외, 산양유, 치즈류, 아이스크림류, 발효유류, ..."
16,prduct_nm,279462,string[python],1,0.00,"[렌위치 NY 샌드위치, 삼치(국내산_해동,전처리,세척전), 숲속산양목장 산양유, ..."
17,mnfctur_cmpny_nm,19269,string[python],327664,48.43,"[존쿡 쉐프의 키친(Johncook chef's kitchen), 영어조합법인 서풍..."
18,mnfctur_de,3909,datetime64[ms],0,0.00,"[2025-10-11 00:00:00, 2025-04-28 00:00:00, 202..."
19,date_basis,3,category,0,0.00,"[제조일, 의뢰일, 선적일]"
20,addr,41343,string[python],0,0.00,"[경기도 안성시 미양면 제2공단2길 25, 전라남도 여수시 화양면 석교로 121, ..."
21,addr_source,5,category,0,0.00,"[제조사소재지, 해외제조업소, 업소주소, 인허가대장, 제조사소재지(보완)]"
22,legal_dong_code,3772,category,47642,7.04,"[4155034000, 4613033000, 5275036000, 416102500..."
23,lat,6656,float32,0,0.00,"[36.975372, 34.708126, 35.68397, 45.9778, 37.3..."
24,lon,6630,float32,0,0.00,"[127.215195, 127.613495, 127.17828, 9.449053, ..."

### 의문사항
- result_value의 "음성,음성,음성,음성,음성" 의미는?

In [5]:
df['judge_result'].value_counts(normalize=True)*100

judge_result
불검출    99.708956
검출      0.291044
Name: proportion, dtype: float64

In [6]:
# @title 식품종류별로 검사결과 검출이 된 품목과 검측률
df['judge_result_numeric'] = df['judge_result'].map({'검출': 1, '불검출': 0}).astype(int)
product_list_tm = df.groupby('train_prdlst_nm')['judge_result_numeric'].mean().sort_values(ascending=False)*100
product_list_tm = product_list_tm[product_list_tm != 0]
product_list_tm

/tmp/ipykernel_437/1131968875.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  product_list_tm = df.groupby('train_prdlst_nm')['judge_result_numeric'].mean().sort_values(ascending=False)*100

train_prdlst_nm
버섯류            13.043478
기타식물류           2.898551
정액,수정란,종란       2.233779
축산물             1.617562
수산가공식품류         0.593824
수산물             0.542901
견과 종실류          0.342466
식육가공품 및 포장육     0.319663
기타기준규격외         0.271064
기타식품류           0.190024
즉석식품류           0.119117
농산가공식품류         0.100959
특수영양식품          0.076982
유가공품류           0.037067
음료류             0.015630
Name: judge_result_numeric, dtype: float64

In [7]:
print(f'검출율이 "0"이 아닌 식품종류 개수는 {len(product_list_tm)} 종류')

검출율이 "0"이 아닌 식품종류 개수는 15 종류

In [8]:
# @리스테리아가 검출된 식품종류만 선택하여 데이터 구성
product_list_non_tm = product_list_tm[product_list_tm == 0]
print(product_list_non_tm.index)
tf = df[df['train_prdlst_nm'].isin(product_list_tm.index)]
print("tf['train_prdlst_nm'] 열(Column)에 들어있는 상품명 중 product_list_non_tm.index에 존재하는 상품명이 단 하나라도 있는가?")
tf['train_prdlst_nm'].isin(product_list_non_tm.index).any()

CategoricalIndex([], categories=['가공식품(전부개정)', '개별인정원료', '견과 종실류', '곡류', ..., '특수의료용도식품', '혼합제제류', '환경검체', '환경오염도조사용'], ordered=False, dtype='category', name='train_prdlst_nm')
tf['train_prdlst_nm'] 열(Column)에 들어있는 상품명 중 product_list_non_tm.index에 존재하는 상품명이 단 하나라도 있는가?

np.False_

In [9]:
summarize_df(tf)

,Column,N_Unique,Dtype,Null_Count,Null_Ratio(%),Sample_Values_5
0,lims_data_key,594253,string[python],0,0.00,"[O002012_250100044_1_5, O000728_250103704_4_3,..."
1,hazard_label,1,category,0,0.00,[리스테리아]
2,judge_result,2,category,0,0.00,"[불검출, 검출]"
3,src_route,2,category,0,0.00,"[domestic, overseas]"
4,data_source,1,category,0,0.00,[식약처]
5,expr_iem_nm,4,category,0,0.00,"[리스테리아모노사이토제네스, 리스테리아 모노사이토제네스, 리스테리아 모노싸이토제네스..."
6,result_value,94,string[python],0,0.00,"[음성,음성,음성,음성,음성, 음성, 음성, 음성, 음성, 음성, 음성, 양성, 양..."
7,result_value_num,2,float32,590894,99.43,"[0.0, 2.0]"
8,judge_stdr,16,string[python],587628,98.89,"[n=5,c=0,m=0/25g, n=5, c=0, m=0/25g, 음성 , 10..."
9,judge_stdr_num,5,float32,594186,99.99,"[100.0, 20.0, 25.0, 1000.0, 0.5]"
10,inspct_instt_code,244,category,0,0.00,"[O002012, O000728, O000130, 1471124, O000473, ..."
11,prdlst_code,800,category,0,0.00,"[C0322020100000, Z3800100000000, C031803000000..."
12,train_prdlst_code,15,category,0,0.00,"[C0322000000000, Z3800000000000, C031800000000..."
13,train_prdlst_nm,15,category,0,0.00,"[즉석식품류, 기타기준규격외, 유가공품류, 농산가공식품류, 식육가공품 및 포장육, ..."
14,train_prdlst_code_2,88,category,0,0.00,"[C0322020000000, Z3800100000000, C031803000000..."
15,train_prdlst_nm_2,88,category,0,0.00,"[즉석섭취.편의식품류, 기타기준규격외, 산양유, 치즈류, 발효유류, 기타 농산가공품..."
16,prduct_nm,256836,string[python],1,0.00,"[렌위치 NY 샌드위치, 삼치(국내산_해동,전처리,세척전), 숲속산양목장 산양유, ..."
17,mnfctur_cmpny_nm,14952,string[python],305953,51.49,"[존쿡 쉐프의 키친(Johncook chef's kitchen), 영어조합법인 서풍..."
18,mnfctur_de,3902,datetime64[ms],0,0.00,"[2025-10-11 00:00:00, 2025-04-28 00:00:00, 202..."
19,date_basis,3,category,0,0.00,"[제조일, 의뢰일, 선적일]"
20,addr,36655,string[python],0,0.00,"[경기도 안성시 미양면 제2공단2길 25, 전라남도 여수시 화양면 석교로 121, ..."
21,addr_source,5,category,0,0.00,"[제조사소재지, 해외제조업소, 업소주소, 인허가대장, 제조사소재지(보완)]"
22,legal_dong_code,3624,category,43631,7.34,"[4155034000, 4613033000, 5275036000, 416502500..."
23,lat,6304,float32,0,0.00,"[36.975372, 34.708126, 35.68397, 45.9778, 37.8..."
24,lon,6278,float32,0,0.00,"[127.215195, 127.613495, 127.17828, 9.449053, ..."
25,judge_result_numeric,2,int64,0,0.00,"[0, 1]"

In [10]:
# tf.groupby('train_prdlst_nm')['judge_result_numeric'].mean().sort_values(ascending=False)*100
tf.groupby('train_prdlst_nm', observed=True)['judge_result_numeric'].mean().sort_values(ascending=False) * 100

train_prdlst_nm
버섯류            13.043478
기타식물류           2.898551
정액,수정란,종란       2.233779
축산물             1.617562
수산가공식품류         0.593824
수산물             0.542901
견과 종실류          0.342466
식육가공품 및 포장육     0.319663
기타기준규격외         0.271064
기타식품류           0.190024
즉석식품류           0.119117
농산가공식품류         0.100959
특수영양식품          0.076982
유가공품류           0.037067
음료류             0.015630
Name: judge_result_numeric, dtype: float64

In [11]:
# @title 식품종류별로 수입 및 국내를 구분하여 검출룰을 판단
detection_rate_by_product_route = (
    tf.groupby(['train_prdlst_nm', 'src_route'], observed=True)['judge_result_numeric']
    .mean()
    .unstack('src_route')
    .fillna(0) * 100
)

# domestic(국내) 수치 기준으로 내림차순 정렬하여 출력
detection_rate_by_product_route.sort_values(by='domestic', ascending=False)

src_route         domestic  overseas
train_prdlst_nm
버섯류              13.043478  0.000000
기타식물류             2.898551  0.000000
정액,수정란,종란         2.233779  0.000000
축산물               0.931677  2.483660
수산물               0.639659  0.537231
수산가공식품류           0.628404  0.000000
견과 종실류            0.342466  0.000000
식육가공품 및 포장육       0.308775  0.497512
기타기준규격외           0.271077  0.000000
기타식품류             0.190295  0.000000
즉석식품류             0.119117  0.000000
농산가공식품류           0.101343  0.000000
음료류               0.015926  0.000000
유가공품류             0.008050  0.114363
특수영양식품            0.000000  0.321027

In [12]:
# @title 검출률 평균이 0보다 큰(양수인) 조합의 데이터만 tf에서 추출하여 tf_filtered
# 1. 식품종류 및 경로(domestic/overseas)별 평균(검출률) 계산
rates = tf.groupby(['train_prdlst_nm', 'src_route'], observed=True)['judge_result_numeric'].transform('mean')

# 2. 검출률 평균이 0보다 큰(0이 아닌) 행들만 필터링하여 tf_filtered 생성
tf_filtered = tf[rates > 0].copy()

# 결과 확인
print(f"기존 tf 행 수: {len(tf)}")
print(f"필터링 후 tf 행 수: {len(tf_filtered)}")

기존 tf 행 수: 594253
필터링 후 tf 행 수: 591849

# 2026_10_7

1. 예측 기간 변경

- 기존: 11일 예측

- 변경: 60일 예측



2. 예측 결과 단위 변경

- 기존: 검체 단위 예측

- 변경: 지역 × 품목군_2단계 × 품목군_3단계 단위로 결과 산출

  (단, 가공식품의 경우 품목군_3단계 × 품목군_4단계)



같은 지역·같은 품목군이라도 하위 품목군이 다르면 각각 별도의 예측 단위로 구분됩니다.



예를 들어 "경기도 안성시 × 견과종실류"만으로는 하나의 단위가 아니고,

"경기도 안성시 × 견과종실류(2단계) × 땅콩 또는 견과류(3단계)"와

"경기도 안성시 × 견과종실류(2단계) × 유지종실류(3단계)"가 각각 별개의 예측 단위가 되어 확률도 따로 산출됩니다.


■ 추가 컬럼

> train_prdlst_code_2    하위 품목군 코드 = 품목군_3단계

>  train_prdlst_nm_2      하위 품목군명



- 기존 품목군 = 2단계(train_prdlst_code)보다 한 단계 아래의 분류입니다.

  하위 단계가 없는 품목은 기존 품목군 값을 그대로 넣었습니다.

>  (단, 가공식품의 경우 품목군_3단계 × 품목군_4단계) 가공식품은 코드가 C로 시작하는 품목입니다.

### **addr(주소) 데이터 전처리**

In [17]:
# 'addr' 컬럼의 문자열을 공백 기준으로 분할하여 '시도'와 '시군구'를 추출합니다.
# 데이터에 결측치나 비정상적인 주소가 있을 수 있으므로 string 타입으로 변환 후 처리합니다.
df['sido'] = df['addr'].astype(str).apply(lambda x: x.split()[0] if len(x.split()) > 0 else '')
df['sigungu'] = df['addr'].astype(str).apply(lambda x: x.split()[1] if len(x.split()) > 1 else '')

# 추출한 '시도'와 '시군구'를 결합하여 '경기도 안성시' 형태의 피처를 생성합니다.
df['region_level_2'] = df['sido'] + ' ' + df['sigungu']

# 결과 확인
df[['addr', 'sido', 'sigungu', 'region_level_2']].head()

,addr,sido,sigungu,region_level_2
0,경기도 안성시 미양면 제2공단2길 25,경기도,안성시,경기도 안성시
1,전라남도 여수시 화양면 석교로 121,전라남도,여수시,전라남도 여수시
2,전북특별자치도 임실군 신덕면 수지로 73-8,전북특별자치도,임실군,전북특별자치도 임실군
3,"VIA V.EMANUELE 62, 23815 INTROBIO (LECCO)",VIA,V.EMANUELE,VIA V.EMANUELE
4,경기도 광주시 오포읍 봉골길33번길 23,경기도,광주시,경기도 광주시

In [18]:
# 숫자(0-9) 및 일부 특수문자를 허용하여 세종시(도움3로) 등 국내 도로명 주소가 감지되지 않도록 개선합니다.
# 한글, 공백, 숫자 이외의 문자(예: 영문 알파벳)가 포함된 행만 필터링합니다.
refined_non_korean_mask = df['sido'].str.contains('[^가-힣\s0-9]', na=False) | df['sigungu'].str.contains('[^가-힣\s0-9]', na=False)
refined_non_korean_df = df[refined_non_korean_mask]

# 결과 확인
print(f"개선된 필터 기준 한글이 아닌 행의 수: {len(refined_non_korean_df)}")
refined_non_korean_df[['addr', 'sido', 'sigungu', 'region_level_2']].head(10)

<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_437/638812706.py:3: SyntaxWarning: invalid escape sequence '\s'
  refined_non_korean_mask = df['sido'].str.contains('[^가-힣\s0-9]', na=False) | df['sigungu'].str.contains('[^가-힣\s0-9]', na=False)
/tmp/ipykernel_437/638812706.py:3: SyntaxWarning: invalid escape sequence '\s'
  refined_non_korean_mask = df['sido'].str.contains('[^가-힣\s0-9]', na=False) | df['sigungu'].str.contains('[^가-힣\s0-9]', na=False)

개선된 필터 기준 한글이 아닌 행의 수: 47762

,addr,sido,sigungu,region_level_2
3,"VIA V.EMANUELE 62, 23815 INTROBIO (LECCO)",VIA,V.EMANUELE,VIA V.EMANUELE
101,"Saifeiya Food Area, Xizi Town, Ningcheng Count...",Saifeiya,Food,Saifeiya Food
108,"5-54-4,ZENIBAKO OTARU-CITY, HOKKAIDO JAPAN","5-54-4,ZENIBAKO","OTARU-CITY,","5-54-4,ZENIBAKO OTARU-CITY,"
151,"2235 S CENTRAL AVENUE, PHOENIX, ARIZONA 85004 USA",2235,S,2235 S
157,ZA UR XABALETA 64640 HELETTE,ZA,UR,ZA UR
159,"QIANYAN VILLAGE DALIANWAN, GANJINGZI DISTRICT,...",QIANYAN,VILLAGE,QIANYAN VILLAGE
209,"35 HERMOU STR. 14452 METAMORFOSSI, ATHENS",35,HERMOU,35 HERMOU
227,"S.S.6 CASILINA KM 181, 400-81057 TEANO (CASERTA)",S.S.6,CASILINA,S.S.6 CASILINA
278,"398902, RUSSIA, LIPETSK CITY, STR. ANGARSKAYA ...","398902,","RUSSIA,","398902, RUSSIA,"
302,"35 HERMOU STR. 14452 METAMORFOSSI, ATHENS",35,HERMOU,35 HERMOU

In [20]:
# 한글이 아닌 문자가 포함된 행을 제외(~ 연산자 사용)하여 한글 데이터만 추출합니다.
korean_df = df[~refined_non_korean_mask].copy()

# 결과 확인
print(f"한글 주소 데이터 수: {len(korean_df)} / 전체 데이터 수: {len(df)}")
display(korean_df[['addr', 'sido', 'sigungu', 'region_level_2']].head(10))

한글 주소 데이터 수: 628769 / 전체 데이터 수: 676531

,addr,sido,sigungu,region_level_2
0,경기도 안성시 미양면 제2공단2길 25,경기도,안성시,경기도 안성시
1,전라남도 여수시 화양면 석교로 121,전라남도,여수시,전라남도 여수시
2,전북특별자치도 임실군 신덕면 수지로 73-8,전북특별자치도,임실군,전북특별자치도 임실군
4,경기도 광주시 오포읍 봉골길33번길 23,경기도,광주시,경기도 광주시
5,경기도 포천시 소흘읍 거친봉이1길 17-23,경기도,포천시,경기도 포천시
6,경기도 광주시 곤지암읍 독고개길86번길 23,경기도,광주시,경기도 광주시
7,충청남도 청양군 대치면 칠갑산로 454,충청남도,청양군,충청남도 청양군
8,"울산광역시 북구 모듈화산업로 251(연암동,3동 1층)",울산광역시,북구,울산광역시 북구
9,"전북특별자치도 군산시 내항2길 312(2,3층 해망동, 군산수산물연구가공거점단지위판...",전북특별자치도,군산시,전북특별자치도 군산시
10,경기도 광주시 초월읍 무갑길 131 (무갑리),경기도,광주시,경기도 광주시